"""Number of iterations for the loops in the experiments."""

FIND_BY_ID = 40
FIND_BY_DESCRIPTION = 40
FIND_BY_CONTENT = 40
TAP = 10
LONG_TAP = 10
MULTI_FINGER_TAP = 10
DRAGNDROP = 10
SWIPE = 40
PINCH_AND_SPREAD = 40
BACK_BUTTON = 200
INPUT_TEXT = 10

FIND_BY_ID_UNIT = 7
FIND_BY_DESCRIPTION_UNIT = 7
FIND_BY_CONTENT_UNIT = 3
TAP_UNIT = 4
LONG_TAP_UNIT = 4
MULTI_FINGER_TAP_UNIT = 5
DRAGNDROP_UNIT = 4
SWIPE_UNIT = 2
PINCH_AND_SPREAD_UNIT = 2
BACK_BUTTON_UNIT = 1
INPUT_TEXT_UNIT = 1
