"""Number of iterations for the loops in the experiments."""

FIND_BY_ID = 40
FIND_BY_DESCRIPTION = 40
FIND_BY_CONTENT = 40
TAP = 10
LONG_TAP = 10
MULTI_FINGER_TAP = 10
DRAGNDROP = 10
SWIPE = 40
PINCH_AND_SPREAD = 40
BACK_BUTTON = 200
