"""Time boundaries for all use cases studied across multiple frameworks."""

FIND_BY_CONTENT_DESCRIPTION = -1 #DELETEME
TAP = -1
LONG_TAP = -1
DOUBLE_TAP = -1
MULTI_FINGER_TAP = -1
DRAGNDROP = -1
DRAGNDROP_UNIT = -1
SWIPE= -1
SWIPE_UNIT = -1
PINCH_AND_SPREAD = -1
BACK_BUTTON = -1
BACK_BUTTON_UNIT = -1
INPUT_TEXT = -1
FIND_BY_DESCRIPTION = -1
FIND_BY_ID = -1
FIND_BY_CONTENT = -1
